name: ist_study
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.2
  cloud_firestore: ^0.14.2
  firebase_messaging: ^7.0.3
  google_sign_in:
  http:
  qrscan: ^0.2.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^0.19.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
